# service, headless service, statefulset, persistent volume claim
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
apiVersion: v1 #service
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    purpose: roboshop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306 #servicePort
      targetPort: 3306 #containerPort

---
apiVersion: v1 #headless service
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
spec:
  clusterIP: None #headless service
  selector:
    purpose: roboshop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306 #servicePort
      targetPort: 3306 #containerPort

---
apiVersion: storage.k8s.io/v1 #storage class
kind: StorageClass
metadata:
  name: mysql-storage-class
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    matchLabels:
      purpose: roboshop
      component: mysql
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless" # headless service name has to match the serviceName in stateful set
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        purpose: roboshop
        component: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: vamsi562/mysql:v1
          imagePullPolicy: always
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 5
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
      volumes:
        - name: mysql-config
          configMap:
            name: mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "mysql-storage-class" #storage class name
        resources:
          requests:
            storage: 1Gi
