---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    purpose: roboshop
    component: user
    tier: backend
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    purpose: roboshop
    component: user
    tier: backend
  namespace: roboshop
spec:
  # Specify replicas to be created
  replicas: 1
  selector:
    matchLabels:
      purpose: roboshop
      component: user
      tier: backend
  template:
    # pod definition
    metadata:
      labels:
        purpose: roboshop
        component: user
        tier: backend
    spec:
      containers:
        - name: user
          image: vamsi562/user:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: user
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 3
            periodSeconds: 15
            initialDelaySeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    purpose: roboshop
    component: user
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 #servicePort
      targetPort: 8080 #containerPort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: roboshop
  labels:
    purpose: roboshop
    component: user
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
